"""Researched Civ II advice; never an executable policy or hidden observation."""

REVISION = 'civ2-prince-guide-2026-09-17-v5'
SOURCES = [
    {'title':'Original Civilization II manual',
     'url':'https://archive.org/details/civ2_manual'},
    {'title':'How to Win Civ2 Before 1750 AD — Lars and Jens Palsberg',
     'url':'https://civfanatics.com/civ2/strategy/win1750ad/'},
    {'title':"Octagon's Strategy for Civ2",
     'url':'https://civfanatics.com/civ2/strategy/octagon/'},
    {'title':'Early Landing Games Strategy Guide — Apolyton',
     'url':'https://apolyton.net/forum/civilization-series/civilization-i-and-civilization-ii/95334-early-landing-games-strategy-guide'},
]

PLAYBOOK = {
    'objective': 'Win this original Prince game, not merely accumulate cities or score. Develop a productive, defended empire, then convert that advantage into a concrete conquest campaign or a completed space race. Advice below is adapted from experienced Civ II players; the guides often assume Deity, larger maps or later editions. Their city caps, dates and fixed research/build sequences are not rules for this game. Actual original rules, observed conditions and currently offered commands take precedence.',
    'decision_order': 'First address an immediate threat, civil disorder, starvation or unsustainable support. Next correct a major bottleneck such as no defenders, an obsolete government, inadequate food or stalled production. Then expand, improve research/trade or execute the current military objective. Finish Turn when useful interventions are complete; repeatedly choosing Finish Turn while a known bottleneck persists is not progress.',
    'productive_turns': 'Original Civ II repeats unit production after a unit is completed: a city still showing Warriors may already have produced several and be starting another. Completion does not automatically switch to Settlers or infrastructure. Reassess the next unit after completion or when the existing garrison already meets the observed need. With no Settlers/Engineers and no city building one, passing turns on military production cannot create an expansion or terrain-work pipeline. Consider changing a suitable, fed city to a worker while retaining necessary defense; do not assume a one-city opening will expand automatically. Production and research advance when turns pass, so let an appropriate build accumulate shields rather than selecting that same item repeatedly. Use the supplied current builds, stored resources, output, garrisons and worker pipeline to distinguish useful waiting from repeating an obsolete choice. Open a city for a concrete change, then choose its native production option separately. A new turn alone is not a reason to inspect every city, and sufficient defense does not imply that another identical defender is the best build.',
    'opening_and_defense': 'A strong default opening is an inexpensive garrison, a Settler for another city, useful tile work, then production suited to the city. Warriors cheaply provide a garrison and permitted martial law; Phalanx or later appropriate defenders give better protection. With restless tribes, an entirely undefended empire is vulnerable even before an enemy is visible. If every city produces Settlers and no military units exist, give high priority to changing at least one productive city to a useful defender. Do not put every city permanently on Settlers.',
    'garrison_and_surplus': 'Compare the observed city garrisons before fortifying another unit. If one city has adequate defenders while others have none, consider distributing appropriate defenders to those cities. Surplus units can scout known frontiers, escort Settlers or assemble for a concrete military objective; repeatedly fortifying weak units in one already defended city has an opportunity cost. Keep enough defense for observed threats, happiness and plausible barbarian risk. Once adequate garrisons are underway or complete, reconsider continued production of the same weak defenders: choose workers, useful infrastructure, trade or stronger military units according to the actual economy and threats. These are alternatives to evaluate, not mandatory moves or fixed garrison counts.',
    'support_and_expansion': 'Count units by their recorded home city as well as by where they stand. Moving or fortifying a unit elsewhere does not transfer its home-city support. Under Despotism, a city supports units up to its population size free of shields; under Monarchy the first three are free. Additional supported units cost one shield each, and Settlers also consume one food per turn under these two governments. Citizens consume two food each. Gross food/shield output is not net surplus: allow for support and other native losses. Building a Settler removes a population point, can remove a productive worked tile, lowers the Despotism free-support allowance and adds another supported unit simultaneously. Check the resulting current budget before another Finish Turn; a city that could build a Settler may be unable to keep it alive afterward. Food stores do not cover a shield-support shortage. The original manual says unsupported units farthest from home are disbanded first, so sending a newly built Settler away does not cure the shortfall. Consider an actually offered production change to stop accumulating unnecessary units, a useful labor allocation, regrowth, or adopting an available Monarchy; founding a legal new city consumes the Settler and ends its old home support. Zero food surplus can sustain the current population but cannot regrow it for another Settler. Do not assume that disbanding, changing a home city or activating an already fortified unit is available: use only offered commands, and do not treat ordinary movement as support relief. These facts identify a constraint, not a forced build or move.',
    'development': 'Expand toward roughly six to eight useful cities as an opening aim when known land, food and happiness allow; this is neither a required count nor a limit. Prefer food and useful trade/production, reasonably close connected cities, and at least one coastal gateway when practical. Do not leave productive land unused while making every city tiny. Preserve positive food surplus and avoid repeatedly producing Settlers before a city can regrow. At a size-one Settler warning, normally delay or change production rather than disband a productive city; deliberate relocation is an exceptional alternative.',
    'government': 'Prioritize reaching Monarchy in the early game and actually adopting it. Discovery alone leaves Despotism in place. If Monarchy is known while a young expanding empire remains in Despotism, strongly favor reviewing the revolution route and accepting its temporary Anarchy when immediate survival permits; do not postpone the benefit indefinitely. Monarchy suits expansion and a supported early army. Consider Republic or Democracy later for a trade/science economy only when food, unit support, happiness and military commitments can sustain them. A conquest empire need not change to Republic merely because it becomes available.',
    'science': 'Keep research purposeful: early Monarchy, then useful Trade and Writing, with military and transport prerequisites matched to the observed map and victory plan. Trade enables Caravans; Writing enables Diplomats. A pre-Gunpowder conquest path can use Monotheism for Crusaders, Feudalism for appropriate defenders/veteran support, and Map Making or Navigation when seas separate targets. Do not wait for every suggested wonder or technology before a favorable local campaign. Research only an actually offered advance, and use original prerequisite paths rather than copying a guide list mechanically.',
    'economy_and_labor': 'Work useful food, shields and trade while avoiding disorder. Roads on worked terrain that gains trade and connections between cities often repay early worker time quickly. Irrigate or mine according to actual terrain, food needs and government; do not improve a tile merely because the command exists. City happiness is an economic constraint: use appropriate garrisons, entertainers/luxuries or buildings when needed, without starving the city. Keep a cash reserve for emergencies and useful purchases; set science as high as sustainable while retaining necessary tax income and luxuries. An actual native purchase quote must justify its cost.',
    'despotism': 'Under original Despotism, a tile that would produce three or more of any one resource produces one less. Ordinary Grassland food 2 plus irrigation 1 therefore still yields 2 before other effects, while ordinary Plains food 1 plus irrigation 1 becomes 2. Compare the benefit of roads, other terrain work and changing government before spending worker turns.',
    'specialization_and_wonders': 'Use food-rich cities for expansion/workers, strong shield cities for military production, and strong trade cities for science/economic improvements. Veteran units from a few suitable military producers are preferable to weak scattered attacks. Build infrastructure for an identified payoff rather than the same queue everywhere. Wonders are optional investments with large opportunity costs; choose ones that support the actual plan and do not leave the empire defenseless to collect them. Caravans can help useful wonders through original offered choices.',
    'trade_and_diplomacy': 'Use contact to learn, trade useful technologies and establish practical peace or alliances. Peace with a useful neighbor can secure a border and a trade partner while Rome develops. Weigh tribute against the cost of a war the current army cannot fight. Caravan delivery produces an immediate gold and research bonus plus an ongoing trade route; each city can retain up to three routes. Demanded goods, foreign partners and overseas trade can be valuable when supply, demand and a practical route are actually observed. Use trade-rich core cities for science and supporting cities for useful Caravans/ships. Diplomats can establish embassies, bribe units or incite cities when those native choices are available and affordable; the actual price, relations and consequences require observation.',
    'war': 'Choose an observed objective and concentrate enough appropriate force to take it, rather than feeding one attacker into a defended city every turn. Use veteran attackers, escorts and favorable defensive staging terrain; protect vulnerable units and avoid exposed stacks that can be destroyed together. Account for known walls and defenders without inventing unseen strength. Keep or supply a garrison in captured cities so attackers can continue. Use transports for overseas objectives; boarding, cargo capacity and landfall remain subject to the original game. Naval bombardment cannot occupy a city: ground forces are still needed.',
    'exploration': 'Explore deliberately toward nearby frontiers, contact, useful settlement sites and routes. Use units suited to scouting while preserving critical Settlers and protecting the empire. Repeatedly moving between the same explored tiles does not discover anything. Once a target or route is no longer useful, reassess the plan rather than oscillating or waiting without purpose.',
    'victory_plan': 'If nearby rivals can be conquered with a supported force, turn production and research toward that campaign. If conquest becomes impractical or the empire can out-research isolated rivals, develop a space-race economy and the required technologies, then assemble and launch through observed original controls. Prepare production and cash for the ship while researching; reaching Space Flight without resources to build it does not finish the race. Apollo and the original ship assembly, fuel, support, energy and flight-time requirements matter; protect the capital and wait for actual successful arrival. Neither a technology lead nor launching a ship is victory. Standard rules can restart defeated civilizations, so historical destruction notices are not proof that every rival is gone.',
    'city_centers': 'Original city squares automatically receive roads and appropriate irrigation/mining, then relevant automatic upgrades. Settlers cannot add ordinary roads, irrigation, mining or railroads to the city square. Improve useful surrounding tiles instead; terrain conversion is a different native-menu action.',
    'continuity': 'Use recent receipts to notice unchanged orders and back-and-forth travel. Current observations override history, and a changed save alone does not establish strategic progress. Unit record IDs compact, so an old ID alone does not identify a current unit. Distances are geometric, not verified routes or movement costs. Advice never authorizes unavailable controls or hidden information.',
}
